version: '2'
services:
  zookeeper:
    container_name: local-zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "42181:2181"
  kafka:
    container_name: local-kafka
    image: wurstmeister/kafka:2.13-2.8.1
    depends_on:
      - zookeeper
    ports:
      - "49092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 43.200.254.74 # 싱글 브로커 환경
      KAFKA_ADVERTISED_PORT: 49092
      KAFKA_CREATE_TOPICS: "webtoon:1:1,board:1:1,review:1:1" # Topic 명 : Partition 개수 : Replica 개수
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock